[package]
name = "breach-walker"
version = "0.1.0"
authors = ["x1a0 <zhangxiao@xzhang.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
